export const XHR_CLIENTS_START = 'XHR_CLIENTS_START'
export const XHR_CLIENTS_SUCCESS = 'XHR_CLIENTS_SUCCESS'
export const XHR_CLIENTS_ERROR = 'XHR_CLIENTS_ERROR'

export const GET_CLIENT = 'GET_CLIENT'

export const SEARCH_CLIENT = 'SEARCH_CLIENT'